In [42]:
import numpy as np
import scipy
import scipy.linalg

In [43]:
a = np.array([
    [1,2,3],
    [2,16,21],
    [4,28,73]
])

In [44]:
l, u = scipy.linalg.lu(a, permute_l=True)
### Поясните, пожалуйста, на вебинаре этот момент с permute
### Функция lu раскладывает матрицу не так, как можно найти в интернете, например здесь:
### https://www.kontrolnaya-rabota.ru/s/matrix/lu-raslogenie/?width=3&height=3&matrix_cells=%5B%5B%221%22%2C%222%22%2C%223%22%5D%2C%5B%222%22%2C%2216%22%2C%2221%22%5D%2C%5B%224%22%2C%2228%22%2C%2273%22%5D%5D
### Из-за этого, матрица L не яыляется треугольной, но произведение L * U дает исходную матрицу.
### В чем отличия алгоритмов?

In [45]:
print(l)
print(u)

[[ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]
 [ 1.    0.    0.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [46]:
b = np.array([1,2,3])

In [47]:
np.linalg.solve(a, b)

array([ 1.01388889,  0.03472222, -0.02777778])

In [48]:
### Решаем через LU разложение

In [54]:
np.dot(l, u)
### Получили первоначальную матрицу, значит разложение выполнено верно

array([[ 1.,  2.,  3.],
       [ 2., 16., 21.],
       [ 4., 28., 73.]])

In [55]:
### Применяем метод решения, как на видео
y = np.linalg.solve(l, b)

In [56]:
y

array([3.  , 0.25, 0.6 ])

In [57]:
x = np.linalg.solve(u, y)

In [58]:
x

array([ 1.01388889,  0.03472222, -0.02777778])